[readme] Show how CARGO_PROFILE can be used for debug build
malept/thermite pull request #51
Opened 2018-06-19 16:20 UTC by mkonicek

In our Ruby project that uses Rust, we integrate Thermite into our build process like this:

```
task build: [:check_ruby_opts, 'thermite:build']
```

It's very useful to be able to iterate on a debug build during development. I change some Rust code, run Ruby tests that call it, and repeat.

Running `CARGO_PROFILE=debug rake build` takes 11s in our project, compared to `rake build` which takes 45s.

I found about the `CARGO_PROFILE` variable by [reading code](https://github.com/malept/thermite/blob/ca07a5141779a21524be06687f423312cab2d836/lib/thermite/tasks.rb#L126). Documenting it in the readme might be useful. This is a big boost to my productivity and might be useful to others.

2018-06-19 16:34 UTC, malept requested changes
Thanks for the PR, I guess just having docs in the `rake` help wasn't enough.

2018-06-19 16:34 UTC, malept commented on README.md
> +By default Thermite will do a release build of your Rust code. To do a debug build instead, set the `CARGO_PROFILE` environment variable to `debug`.
Can each line be 100 characters long (like the other lines in the README)?

2018-06-19 16:34 UTC, malept commented on README.md
> +For example, you can run `CARGO_PROFILE=debug rake build`.
`rake thermite:build`, `build` is specific to a user's `Rakefile`.

2018-06-21 12:09 UTC, mkonicek commented
Thanks a lot @malept for having a look! I made the lines fit into the 100 character limit, and updated the example to say `rake thermite:build`.

2018-06-21 18:26 UTC, malept approved these changes

2018-06-21 18:26 UTC, merged

2018-06-21 18:27 UTC, malept commented
Thanks again!